In [8]:
a = 100

In [9]:
a

100

In [3]:
c= {}

In [4]:
c

{}

In [6]:
c["test"]="abc"

In [10]:
c

{'test': 'abc'}

In [11]:
from pandas import Series, DataFrame

In [13]:
a = Series(["A", "B", "C", "D", "E"])

In [14]:
a

0    A
1    B
2    C
3    D
4    E
dtype: object

In [15]:
b = Series({"andrew":30, "sera":50, "thomas":20})

In [16]:
b

andrew    30
sera      50
thomas    20
dtype: int64

In [17]:
c=b.add(10)

In [18]:
c

andrew    40
sera      60
thomas    30
dtype: int64

In [19]:
import pandas as pd
data = {'state':['Ohio','Ohio','Ohio','Nevada', 'Nevada'], 'year':[2000,2001,2002,2001,2002],
       'pop':[1.5,1.7,3.6,2.4,2.9]}
frame = DataFrame(data)
frame

   pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [20]:
frame.to_excel("d:\\test01.xlsx")

In [22]:
for i in frame.columns:
    print(i)

pop
state
year

In [23]:
frame.columns=["change1","change2","change3"]

In [24]:
frame

   change1 change2  change3
0      1.5    Ohio     2000
1      1.7    Ohio     2001
2      3.6    Ohio     2002
3      2.4  Nevada     2001
4      2.9  Nevada     2002

In [25]:
frame.index = frame.A

AttributeError: 'DataFrame' object has no attribute 'A'

In [26]:
frame.index = frame.change1

In [27]:
frame

         change1 change2  change3
change1
1.5          1.5    Ohio     2000
1.7          1.7    Ohio     2001
3.6          3.6    Ohio     2002
2.4          2.4  Nevada     2001
2.9          2.9  Nevada     2002

In [31]:
frame.change3 = 2001
frame

         change1 change2  change3
change1
1.5          1.5    Ohio     2001
1.7          1.7    Ohio     2001
3.6          3.6    Ohio     2001
2.4          2.4  Nevada     2001
2.9          2.9  Nevada     2001

In [32]:
frame["debt"] = 16.5

In [33]:
frame

         change1 change2  change3  debt
change1
1.5          1.5    Ohio     2001  16.5
1.7          1.7    Ohio     2001  16.5
3.6          3.6    Ohio     2001  16.5
2.4          2.4  Nevada     2001  16.5
2.9          2.9  Nevada     2001  16.5

In [42]:
frame['estern']=frame.change2=='Ohio'
frame

         change1 change2  change3  debt  estern
change1
1.5          1.5    Ohio     2001  16.5    True
1.7          1.7    Ohio     2001  16.5    True
3.6          3.6    Ohio     2001  16.5    True
2.4          2.4  Nevada     2001  16.5   False
2.9          2.9  Nevada     2001  16.5   False

In [43]:
frame.T

change1   1.5   1.7   3.6     2.4     2.9
change1   1.5   1.7   3.6     2.4     2.9
change2  Ohio  Ohio  Ohio  Nevada  Nevada
change3  2001  2001  2001    2001    2001
debt     16.5  16.5  16.5    16.5    16.5
estern   True  True  True   False   False

In [44]:
frame.T

change1   1.5   1.7   3.6     2.4     2.9
change1   1.5   1.7   3.6     2.4     2.9
change2  Ohio  Ohio  Ohio  Nevada  Nevada
change3  2001  2001  2001    2001    2001
debt     16.5  16.5  16.5    16.5    16.5
estern   True  True  True   False   False

In [45]:
frame2 = frame.T

In [46]:
frame2

change1   1.5   1.7   3.6     2.4     2.9
change1   1.5   1.7   3.6     2.4     2.9
change2  Ohio  Ohio  Ohio  Nevada  Nevada
change3  2001  2001  2001    2001    2001
debt     16.5  16.5  16.5    16.5    16.5
estern   True  True  True   False   False

In [47]:
frame2.T

        change1 change2 change3  debt estern
change1
1.5         1.5    Ohio    2001  16.5   True
1.7         1.7    Ohio    2001  16.5   True
3.6         3.6    Ohio    2001  16.5   True
2.4         2.4  Nevada    2001  16.5  False
2.9         2.9  Nevada    2001  16.5  False

In [87]:
filename = r"C:\Users\Administrator\Downloads\상가업소정보\상가업소_201706_01.csv"

In [88]:
import os
os.path.isfile(filename)

True

In [89]:
import pandas as pd

In [90]:
df = pd.read_csv(filename,engine="python")

In [91]:
df

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,19911397,커피빈,코리아선릉로93길점,Q,음식,Q12,커피점/카페,Q12A01,커피전문점/카페/다방,I56220,...,1168010100106960042022041,NaN,서울특별시 강남구 선릉로93길 6,135080,6149.0,NaN,NaN,NaN,127.047883,37.505675
1,19911801,프로포즈,NaN,Q,음식,Q09,유흥주점,Q09A01,호프/맥주,I56219,...,1154510200101620001017748,NaN,서울특별시 금천구 가산로 34-6,153010,8545.0,NaN,1,NaN,126.899220,37.471711
2,19912201,싱싱커피&토스트,NaN,Q,음식,Q07,패스트푸드,Q07A10,토스트전문,I56192,...,2653010400105780000002037,산업용품유통상가,부산광역시 사상구 괘감로 37,617726,46977.0,NaN,1,26,128.980455,35.159774
3,19905471,와라와라호프,NaN,Q,음식,Q09,유흥주점,Q09A01,호프/맥주,I56219,...,1168010600106040000014378,대치상가,서울특별시 강남구 남부순환로 2933,135280,6280.0,NaN,1,NaN,127.061026,37.493922
4,19932756,가락사우나내스낵,NaN,F,생활서비스,F09,대중목욕탕/휴게,F09A02,사우나/증기탕/온천,S96121,...,1171010500102560005010490,NaN,서울특별시 송파구 가락로 71,138846,5690.0,NaN,1,NaN,127.104071,37.500249
5,19975850,허술한집,NaN,Q,음식,Q04,분식,Q04A01,라면김밥분식,I56194,...,1150010800100450031005883,NaN,서울특별시 강서구 공항대로3길 9,157812,7619.0,NaN,1,NaN,126.809957,37.562013
6,19976567,씨유씨로지스틱스,NaN,D,소매,D03,종합소매점,D03A01,편의점,G47122,...,1114016800100050002022586,순화빌딩,서울특별시 중구 서소문로 89,100731,4516.0,NaN,NaN,1501,126.970813,37.562587
7,19977290,피자마루,약수점,Q,음식,Q07,패스트푸드,Q07A01,피자전문,I56192,...,1114016200103720095000001,현진빌딩,서울특별시 중구 동호로7길 37,100450,4596.0,NaN,1,NaN,127.010861,37.552153
8,19979419,원일슈퍼,NaN,D,소매,D03,종합소매점,D03A02,수퍼마켓,G47121,...,1174010900103150006009092,원일빌딩,서울특별시 강동구 올림픽로92길 6,134020,5323.0,NaN,1,NaN,127.127190,37.547655
9,19979960,홍능갈비,NaN,Q,음식,Q01,한식,Q01A02,갈비/삼겹살,I56111,...,1150010300110860003013118,NaN,서울특별시 강서구 화곡로18길 31,157010,7718.0,NaN,1,NaN,126.836078,37.538927
10,19980199,프렌즈피씨방,NaN,N,관광/여가/오락,N01,PC/오락/당구/볼링등,N01A01,인터넷PC방,R91222,...,1147010300101460001014147,NaN,서울특별시 양천구 남부순환로 353,158090,7920.0,NaN,1,NaN,126.828910,37.535667
11,19980266,진커피호프,NaN,Q,음식,Q09,유흥주점,Q09A01,호프/맥주,I56219,...,1147010100109470004003423,NaN,서울특별시 양천구 오목로 154,158070,8019.0,NaN,1,NaN,126.854423,37.524654
12,19980870,김명희자연비누,NaN,D,소매,D03,종합소매점,D03B04,시장/종합상가,G47129,...,1147010100102940005005912,NaN,서울특별시 양천구 신목로5길 14,158070,8014.0,NaN,2,NaN,126.872446,37.517863
13,19983964,대성정육점,NaN,D,소매,D01,음/식료품소매,D01A03,정육점,G47212,...,1114016200100430014023177,NaN,서울특별시 중구 다산로36길 93,100815,4584.0,NaN,1,NaN,127.019447,37.560271
14,19969945,에브리돈,NaN,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,1141011900103070003002306,NaN,서울특별시 서대문구 응암로 65,120130,3681.0,NaN,1,NaN,126.910288,37.579029
15,19971229,라이브7080,NaN,Q,음식,Q09,유흥주점,Q09A10,룸살롱/단란주점,I56211,...,1168010800101060018005893,NaN,서울특별시 강남구 언주로136길 7,135010,6058.0,NaN,NaN,NaN,127.036140,37.517348
16,19971398,우리식당,NaN,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,1121510700102070003018172,NaN,서울특별시 광진구 광나루로26길 16,143926,5022.0,NaN,NaN,NaN,127.076812,37.545461
17,19973708,왕실,NaN,Q,음식,Q12,커피점/카페,Q12A01,커피전문점/카페/다방,I56220,...,1114012700101050000019781,NaN,서울특별시 중구 남대문로 52-13,100810,4535.0,NaN,1,NaN,126.982419,37.562274
18,19974666,신호건강원,NaN,D,소매,D10,건강/미용식품,D10A07,건강원,G47216,...,1150010300103690053013643,NaN,서울특별시 강서구 가로공원로82길 42-3,157010,7765.0,NaN,1,NaN,126.840285,37.535419
19,19989422,Mr.피터팬,NaN,Q,음식,Q04,분식,Q04A01,라면김밥분식,I56194,...,1171010300103990017025154,송주빌라,서울특별시 송파구 올림픽로45길 22,138040,5537.0,NaN,1,NaN,127.115873,37.527477
20,19991286,GOVI,NaN,Q,음식,Q09,유흥주점,Q09A01,호프/맥주,I56219,...,1153010200107670148021210,NaN,서울특별시 구로구 도림로 53,152050,8314.0,NaN,1,NaN,126.889734,37.488625
21,19999875,제이씨코퍼레이션,NaN,D,소매,D02,선물/팬시/기념품,D02A05,토산품/기념품점,G47842,...,1156012700100240000037460,삼천리아파트,서울특별시 영등포구 선유서로 115,150103,7269.0,101,NaN,804,126.885320,37.526139
22,20001640,에터미,NaN,D,소매,D16,화장품소매,D16A01,화장품판매점,G47813,...,1162010300110620002023715,NaN,서울특별시 관악구 남현1길 38-9,151800,8806.0,NaN,NaN,NaN,126.979695,37.475560
23,20002036,서울소망흑염소,NaN,D,소매,D10,건강/미용식품,D10A07,건강원,G47216,...,1154510300109010024005627,NaN,서울특별시 금천구 시흥대로50길 30,153030,8630.0,NaN,1,NaN,126.903743,37.451525
24,20004707,커피빈,코리아교대점,Q,음식,Q12,커피점/카페,Q12A01,커피전문점/카페/다방,I56220,...,1165010800116570005024412,카이스시스템빌딩,서울특별시 서초구 서초중앙로 118,137070,6634.0,NaN,1,NaN,127.014217,37.492388
25,20006330,코롱식당,NaN,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,1154510100100600004015530,코오롱테크노밸리,서울특별시 금천구 디지털로9길 56,153770,8512.0,NaN,NaN,102,126.886859,37.480390
26,19993199,고려대학교교육관쎄리오점,NaN,Q,음식,Q12,커피점/카페,Q12A01,커피전문점/카페/다방,I56220,...,1129012500100010002039525,고려대학교안암캠퍼스(인문사회계),서울특별시 성북구 안암로 145,136701,2841.0,NaN,1,32,127.031702,37.588485
27,19996819,전주식당,NaN,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,1153010200104060010000019,구로치안센터,서울특별시 구로구 경인로 577,152887,8212.0,D,NaN,17,126.880898,37.504067
28,19998566,SKY,NaN,Q,음식,Q04,분식,Q04A01,라면김밥분식,I56194,...,1162010100116040034030449,NaN,서울특별시 관악구 관악로12길 23,151050,8788.0,NaN,NaN,NaN,126.953735,37.478135
29,19999456,다락방,NaN,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,1144010200102550023002336,NaN,서울특별시 마포구 마포대로 112-5,121803,4213.0,NaN,1,NaN,126.952127,37.544646
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
696489,12518884,쿱스토어,양천목동점,Q,음식,Q08,제과제빵떡케익,Q08A01,제과점,I56191,...,1147010200107720006000001,선훈아이엔지빌딩,서울특별시 양천구 목동중앙남로 3,158818,7964.0,NaN,NaN,NaN,126.869281,37.534943
696490,12518894,황진이,NaN,Q,음식,Q09,유흥주점,Q09A10,룸살롱/단란주점,I56211,...,1130510100100420212027917,유창빌딩,서울특별시 강북구 월계로 7,142804,1220.0,NaN,NaN,NaN,127.031053,37.609708
696491,12520154,다이다이,NaN,Q,음식,Q09,유흥주점,Q09A01,호프/맥주,I56219,...,1174010500104390000003220,NaN,서울특별시 강동구 양재대로 1448,134814,5356.0,NaN,NaN,NaN,127.139319,37.535066
696492,12520159,마자리스,NaN,Q,음식,Q06,양식,Q06A01,정통양식/경양식,I56114,...,1111016500101910000009707,NaN,서울특별시 종로구 율곡로 215-6,110500,3100.0,NaN,NaN,NaN,127.002863,37.576531
696493,12520532,영철닭발,NaN,Q,음식,Q05,닭/오리요리,Q05A10,닭내장/닭발요리,I56111,...,1138010800100140007018621,NaN,서울특별시 은평구 서오릉로 95,122895,3404.0,NaN,1,113,126.920576,37.608254
696494,12520533,GS25,편의점,D,소매,D03,종합소매점,D03A01,편의점,G47122,...,1150010300100240552016506,NaN,서울특별시 강서구 까치산로 71,157866,7679.0,NaN,1,NaN,126.846801,37.545060
696495,12520534,우리오리,NaN,Q,음식,Q06,양식,Q06A01,정통양식/경양식,I56114,...,2611012200100520007007445,NaN,부산광역시 중구 흑교로45번길 32,600083,48966.0,NaN,NaN,7,129.021707,35.103817
696496,12521663,세븐일레븐,부산온천금강점,D,소매,D03,종합소매점,D03A01,편의점,G47122,...,2626010800100460006014160,성완아이렉스,부산광역시 동래구 금강로 160-1,607831,47708.0,NaN,NaN,NaN,129.081786,35.222631
696497,12521668,home101,NaN,Q,음식,Q04,분식,Q04A01,라면김밥분식,I56194,...,1117012100100320028015280,NaN,서울특별시 용산구 새창로20길 3,140832,4356.0,NaN,NaN,NaN,126.959446,37.538322
696498,12521920,스시훈,NaN,Q,음식,Q03,일식/수산물,Q03A03,음식점-초밥전문,I56113,...,1144010900100950001006362,NaN,서울특별시 마포구 숭문길 34,121872,4138.0,NaN,NaN,NaN,126.945527,37.548029
696499,12521926,온족,NaN,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,2647010200104490027007654,NaN,부산광역시 연제구 과정로287번길 6,611815,47555.0,NaN,NaN,NaN,129.095689,35.188037
696500,12521927,엄지척대게,NaN,Q,음식,Q03,일식/수산물,Q03A10,바닷가재/게요리전문,I56111,...,2623011100105450003004393,NaN,부산광역시 부산진구 가야대로482번길 35,614813,47327.0,NaN,NaN,NaN,129.024815,35.151412
696501,12521928,피러팻,NaN,Q,음식,Q12,커피점/카페,Q12A01,커피전문점/카페/다방,I56220,...,1120011400106850489027875,NaN,서울특별시 성동구 서울숲2길 8,133825,4768.0,NaN,NaN,NaN,127.039520,37.547515
696502,12521929,이미경맛국수,NaN,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,2623010300102590003022691,NaN,부산광역시 부산진구 서면문화로 8-4,614844,47256.0,NaN,NaN,NaN,129.058129,35.158553
696503,12521933,맛의축제,NaN,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,1121510100102330053026447,NaN,서울특별시 광진구 동일로72길 28,143903,4912.0,NaN,1,NaN,127.079030,37.565644
696504,12522174,돈통,NaN,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,1162010100104640041000001,은선파인빌,서울특별시 관악구 중앙길 133,151823,8747.0,1,NaN,NaN,126.947900,37.486301
696505,12522182,백궁양꼬치,NaN,Q,음식,Q09,유흥주점,Q09A03,꼬치구이전문점,I56219,...,1150010300109270006024868,NaN,서울특별시 강서구 강서로5나길 118,157910,7776.0,NaN,NaN,NaN,126.841581,37.528448
696506,12522184,맷돌빈대떡,NaN,Q,음식,Q09,유흥주점,Q09A01,호프/맥주,I56219,...,1126010300102070033031717,NaN,서울특별시 중랑구 중랑역로 6,131878,2117.0,NaN,NaN,NaN,127.077029,37.594786
696507,12522185,구포고깃집,NaN,Q,음식,Q01,한식,Q01A99,기타고기요리,I56111,...,2632010500107000054008328,NaN,부산광역시 북구 시랑로 9-1,616803,46600.0,NaN,NaN,NaN,129.004507,35.204620
696508,12522511,양곱창정말,NaN,Q,음식,Q01,한식,Q01A03,곱창/양구이전문,I56111,...,2623010400108410239031956,NaN,부산광역시 부산진구 범일로154번길 50,614827,47363.0,NaN,NaN,NaN,129.062117,35.143672
696509,12522525,이레찌개마을막국수,NaN,Q,음식,Q04,분식,Q04A02,국수/만두/칼국수,I56194,...,1123010300108920048032069,NaN,서울특별시 동대문구 약령서길 36,130864,2569.0,NaN,NaN,NaN,127.036273,37.579944
696510,12522572,투썸플레이스,아차산역점,Q,음식,Q12,커피점/카페,Q12A01,커피전문점/카페/다방,I56220,...,1121510200102560012006436,NaN,서울특별시 광진구 천호대로 642,143849,4987.0,NaN,2,1,127.088146,37.553307
696511,12522578,에머이,이태원점,Q,음식,Q09,유흥주점,Q09A01,호프/맥주,I56219,...,1117013000101270012009689,스카이하이,서울특별시 용산구 이태원로 180,140858,4406.0,NaN,NaN,NaN,126.994171,37.534217
696512,12522585,Press,NaN,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,1117013000100040006009022,NaN,서울특별시 용산구 회나무로42길 10,140857,4346.0,NaN,NaN,NaN,126.995646,37.540663
696513,12523217,토미야,NaN,Q,음식,Q03,일식/수산물,Q03A02,음식점-일식,I56113,...,1144012500102530006027901,NaN,서울특별시 마포구 월드컵로 120-1,121847,3971.0,NaN,NaN,NaN,126.907658,37.559110
696514,12523676,J&Y헤어,NaN,F,생활서비스,F01,이/미용/건강,F01A01,여성미용실,S96112,...,1153010700100700011010659,NaN,서울특별시 구로구 고척로22길 78,152803,8266.0,NaN,NaN,NaN,126.847160,37.498219
696515,12523677,젠틀맨클럽,NaN,F,생활서비스,F01,이/미용/건강,F01A01,여성미용실,S96112,...,1132010700105450002015870,NaN,서울특별시 도봉구 우이천로4다길 75,132917,1477.0,NaN,1,NaN,127.039197,37.636950
696516,12523515,어니언베이커리,NaN,Q,음식,Q08,제과제빵떡케익,Q08A01,제과점,I56191,...,1168010100107010000022644,공무원연금공단,서울특별시 강남구 언주로 508,135706,6152.0,NaN,NaN,NaN,127.042725,37.503948
696517,12523558,제퍼,NaN,Q,음식,Q12,커피점/카페,Q12A01,커피전문점/카페/다방,I56220,...,2626010900107490005007920,NaN,부산광역시 동래구 사직로 45,607861,47874.0,NaN,NaN,NaN,129.059911,35.194422
696518,12524154,탐앤탐스,더블유디호텔신림점,Q,음식,Q12,커피점/카페,Q12A01,커피전문점/카페/다방,I56220,...,1162010200114320079000001,NaN,서울특별시 관악구 신림로 349,151892,8760.0,NaN,NaN,NaN,126.929310,37.485503

In [54]:
df.head()

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,19943193,프리즐,NaN,Q,음식,Q04,분식,Q04A01,라면김밥분식,I56194,...,4136025321106720001024396,NaN,경기도 남양주시 진접읍 봉현로 14,472865,12013.0,NaN,3,NaN,127.181143,37.715402
1,19943449,최씨네별난맛집,NaN,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,4125010400104940034000001,NaN,경기도 동두천시 광암로33번길 15,483040,11321.0,NaN,1,NaN,127.085525,37.896127
2,19946985,페리카나,NaN,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4113310900101540044066461,NaN,경기도 성남시 중원구 마지로155번길 25-7,462839,13406.0,NaN,1,NaN,127.149042,37.428063
3,19947331,한우장다리식당,NaN,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,4113510300100430009011063,NaN,경기도 성남시 분당구 내정로119번길 20,463848,13609.0,NaN,1,NaN,127.113929,37.372101
4,19947348,우체국커피자동판매기,NaN,D,소매,D25,기타판매업,D25A18,자동판매기운영,G47991,...,4113110100124820000024208,프린스컨벤션센터,경기도 성남시 수정구 산성대로 297,461163,13354.0,NaN,1,NaN,127.149640,37.442115

In [55]:
type(df)

pandas.core.frame.DataFrame

In [56]:
df.columns

Index(['상가업소번호', '상호명', '지점명', '상권업종대분류코드', '상권업종대분류명', '상권업종중분류코드',
       '상권업종중분류명', '상권업종소분류코드', '상권업종소분류명', '표준산업분류코드', '표준산업분류명', '시도코드',
       '시도명', '시군구코드', '시군구명', '행정동코드', '행정동명', '법정동코드', '법정동명', '지번코드',
       '대지구분코드', '대지구분명', '지번본번지', '지번부번지', '지번주소', '도로명코드', '도로명', '건물본번지',
       '건물부번지', '건물관리번호', '건물명', '도로명주소', '구우편번호', '신우편번호', '동정보', '층정보',
       '호정보', '경도', '위도'],
      dtype='object')

In [57]:
df.상호명

0                    프리즐
1                최씨네별난맛집
2                   페리카나
3                한우장다리식당
4             우체국커피자동판매기
5                     진주
6                 딸기원방아간
7                   낙원떡집
8                  오언니김치
9                 투썸플레이스
10                새마을튀김집
11            이마트안양LG화장품
12                  7080
13                 그랜드식당
14                  맛짱식당
15                   영미네
16                 참치전문점
17              양씨네아바이순대
18                  우미통닭
19              행주산성국제타운
20            청원하이퍼자동판매기
21                  장미식당
22                강동손칼국수
23                  아미식당
24                산약초건강원
25                  왕벌식당
26                미리네먹거리
27                양동큰대문집
28                  천태만상
29            대동현대마트생선코너
               ...
948413          명랑시대쌀핫도그
948414              카페&비
948415            충주호당내과
948416                돈탑
948417              정성가든
948418                고방
948419            맛사랑보신탕
948420             풀잎소주방
948421    그남자의모밀소바,손만두전골
948422           고구마숯불구이
948423                홀바
948424             세븐일레븐
948425             미스사이공
948426              꼬지사께
948427         수제다이어트ANB
948428              세류명가
948429          부드러울윤케이크
948430                 몽
948431                점엽
948432              수헤어샵
948433              헤어베리
948434              HAVE
948435             머리하는집
948436             고다리조트
948437             카리스커피
948438               엘프바
948439             전주삼계탕
948440               갯마을
948441             제이앤로제
948442               용팔이
Name: 상호명, Length: 948443, dtype: object

In [92]:
df[df.상호명 =="명랑시대쌀핫도그"]

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
592753,12075075,명랑시대쌀핫도그,경성대점,Q,음식,Q07,패스트푸드,Q07A03,핫도그,I56192,...,2629010600104270021001023,NaN,부산광역시 남구 용소로 30,608020,48498.0,NaN,NaN,NaN,129.100722,35.134602
595224,12080330,명랑시대쌀핫도그,NaN,Q,음식,Q07,패스트푸드,Q07A03,핫도그,I56192,...,1123010900103280000009676,NaN,서울특별시 동대문구 이문로 28,130090,2446.0,NaN,NaN,NaN,127.055995,37.589826
616879,12083222,명랑시대쌀핫도그,NaN,Q,음식,Q07,패스트푸드,Q07A03,핫도그,I56192,...,2623011000102710039047534,NaN,부산광역시 부산진구 대학로 16,614010,47330.0,NaN,NaN,NaN,129.036822,35.154041
617358,12081838,명랑시대쌀핫도그,중랑구청점,Q,음식,Q07,패스트푸드,Q07A03,핫도그,I56192,...,1126010600106670000001834,금강프라자,서울특별시 중랑구 신내로 82,131130,2067.0,NaN,NaN,NaN,127.095547,37.606679
621367,12103062,명랑시대쌀핫도그,홍대입구점,Q,음식,Q07,패스트푸드,Q07A03,핫도그,I56192,...,1144012000104860000011574,서교푸르지오,서울특별시 마포구 홍익로 10,121837,4055.0,101,NaN,117,126.923740,37.553716
622596,12227068,명랑시대쌀핫도그,NaN,Q,음식,Q04,분식,Q04A01,라면김밥분식,I56194,...,2629010600100500081000279,라끄베르원룸,부산광역시 남구 수영로334번길 48,608804,48512.0,NaN,NaN,102,129.103435,35.136470
633454,12095464,명랑시대쌀핫도그,NaN,Q,음식,Q07,패스트푸드,Q07A03,핫도그,I56192,...,2632010200122760003015391,웰빙프라자,부산광역시 북구 화명대로 34,616120,46526.0,NaN,NaN,NaN,129.011918,35.234538
634871,12120169,명랑시대쌀핫도그,상계백병원점,Q,음식,Q07,패스트푸드,Q07A03,핫도그,I56192,...,1135010500107490008000889,삼양빌딩,서울특별시 노원구 동일로 1350,139832,1756.0,NaN,NaN,NaN,127.062315,37.649246
639440,12228779,명랑시대쌀핫도그,NaN,Q,음식,Q07,패스트푸드,Q07A03,핫도그,I56192,...,1141011000101290050027472,NaN,서울특별시 서대문구 북아현로 28,120819,3756.0,NaN,1,NaN,126.956724,37.559932
641101,12108938,명랑시대쌀핫도그,NaN,Q,음식,Q07,패스트푸드,Q07A03,핫도그,I56192,...,2611013100100120001000001,NaN,부산광역시 중구 광복로39번길 6,600051,48947.0,NaN,NaN,NaN,129.029608,35.099739
641827,12229363,명랑시대쌀핫도그,중동점,Q,음식,Q07,패스트푸드,Q07A03,핫도그,I56192,...,2635010600113940172010734,NaN,부산광역시 해운대구 중동1로 24,612847,48095.0,NaN,NaN,NaN,129.162047,35.163117
643554,12341975,명랑시대쌀핫도그,목동점,Q,음식,Q07,패스트푸드,Q07A03,핫도그,I56192,...,1147010200109070005016350,목동가든스위트,서울특별시 양천구 목동서로 65,158729,7983.0,NaN,1,NaN,126.878710,37.536141
644415,12419983,명랑시대쌀핫도그,암사역점,Q,음식,Q07,패스트푸드,Q07A03,핫도그,I56192,...,1174010900102870000007545,NaN,서울특별시 강동구 올림픽로 770,134867,5318.0,NaN,NaN,NaN,127.127640,37.549776
645407,12442183,명랑시대쌀핫도그,봉화산역점,Q,음식,Q07,패스트푸드,Q07A03,핫도그,I56192,...,1126010600106460000000300,금강리빙스텔,서울특별시 중랑구 신내로 211,131872,2024.0,NaN,NaN,NaN,127.092597,37.616424
645410,12328577,명랑시대쌀핫도그,구남점,Q,음식,Q07,패스트푸드,Q07A03,핫도그,I56192,...,2632010500110950002001199,삼정그린코아,부산광역시 북구 백양대로1016번길 10,616753,46637.0,NaN,NaN,NaN,128.995094,35.195530
645696,12437165,명랑시대쌀핫도그,연신내점,Q,음식,Q07,패스트푸드,Q07A03,핫도그,I56192,...,1138010400103990007034521,NaN,서울특별시 은평구 연서로29길 8,122809,3330.0,NaN,1,8,126.919244,37.618910
646492,12446148,명랑시대쌀핫도그,반송점,Q,음식,Q07,패스트푸드,Q07A03,핫도그,I56192,...,2635010100100620493004508,과일가게,부산광역시 해운대구 윗반송로51번길 84-20,612800,48007.0,NaN,NaN,NaN,129.156531,35.230863
646504,12448519,명랑시대쌀핫도그,창동점,Q,음식,Q07,패스트푸드,Q07A03,핫도그,I56192,...,1132010700100740008013804,NaN,서울특별시 도봉구 노해로63길 78,132903,1405.0,NaN,NaN,NaN,127.046317,37.652578
647247,12446614,명랑시대쌀핫도그,휘경여고점,Q,음식,Q07,패스트푸드,Q07A03,핫도그,I56192,...,1123010400100010205041074,NaN,서울특별시 동대문구 한천로 242,130848,2512.0,NaN,NaN,NaN,127.068587,37.582493
650133,12435410,명랑시대쌀핫도그,NaN,Q,음식,Q07,패스트푸드,Q07A06,도너츠전문,I56191,...,2644010400132380014000001,NaN,부산광역시 강서구 명지오션시티4로 64,618814,46765.0,NaN,NaN,NaN,128.903260,35.083304
651011,12447486,명랑시대쌀핫도그,NaN,Q,음식,Q07,패스트푸드,Q07A03,핫도그,I56192,...,1168010100107560018024268,삼미빌딩,서울특별시 강남구 선릉로 313,135927,6218.0,NaN,NaN,NaN,127.051910,37.497598
651639,12339571,명랑시대쌀핫도그,신모라점,Q,음식,Q07,패스트푸드,Q07A03,핫도그,I56192,...,2653010200113620000001366,우신모라아파트,부산광역시 사상구 백양대로 880,617755,46931.0,NaN,NaN,NaN,128.991309,35.183131
652651,12100002,명랑시대쌀핫도그,덕천점,Q,음식,Q07,패스트푸드,Q07A03,핫도그,I56192,...,2632010400104030029009270,NaN,부산광역시 북구 만덕대로16번길 22,616820,46576.0,NaN,NaN,NaN,129.007204,35.209555
652817,12430666,명랑시대쌀핫도그,화곡점,Q,음식,Q07,패스트푸드,Q07A03,핫도그,I56192,...,1150010300101090016017699,NaN,서울특별시 강서구 화곡로 196,157872,7721.0,NaN,1,NaN,126.842985,37.543005
653029,12439350,명랑시대쌀핫도그,경성대2호점,Q,음식,Q07,패스트푸드,Q07A03,핫도그,I56192,...,2629010600104050000001151,대연맨션,부산광역시 남구 수영로 289,608810,48434.0,NaN,NaN,NaN,129.097789,35.136801
653037,12464009,명랑시대쌀핫도그,개봉역점,Q,음식,Q07,패스트푸드,Q07A03,핫도그,I56192,...,1153010700102030009009554,KS프리미어빌딩,서울특별시 구로구 남부순환로97길 3,152809,8328.0,NaN,NaN,NaN,126.858239,37.493984
653074,12340270,명랑시대쌀핫도그,NaN,Q,음식,Q07,패스트푸드,Q07A03,핫도그,I56192,...,2614010300103500028004185,NaN,부산광역시 서구 구덕로 330,602813,49211.0,NaN,NaN,NaN,129.016339,35.113228
653904,12466377,명랑시대쌀핫도그,남산점,Q,음식,Q07,패스트푸드,Q07A03,핫도그,I56192,...,2641010400100200012006482,NaN,부산광역시 금정구 팔송로 19,609813,46219.0,NaN,NaN,NaN,129.090487,35.272029
657371,12526062,명랑시대쌀핫도그,방화점,Q,음식,Q07,패스트푸드,Q07A03,핫도그,I56192,...,1150010900108290004000546,금강프라자빌딩,서울특별시 강서구 금낭화로 135,157857,7510.0,NaN,1,NaN,126.812418,37.577436
657721,12540156,명랑시대쌀핫도그,잠실신천역점,Q,음식,Q07,패스트푸드,Q07A03,핫도그,I56192,...,1171010100101840011000648,승정빌딩,서울특별시 송파구 석촌호수로 60,138861,5558.0,NaN,NaN,NaN,127.085528,37.510901
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
675239,12491454,명랑시대쌀핫도그,NaN,Q,음식,Q07,패스트푸드,Q07A03,핫도그,I56192,...,2638010400105880001017966,NaN,부산광역시 사하구 하신번영로201번길 13,604838,49431.0,NaN,NaN,NaN,128.957450,35.098924
675738,12555737,명랑시대쌀핫도그,NaN,Q,음식,Q07,패스트푸드,Q07A03,핫도그,I56192,...,1150010300108970015012025,NaN,서울특별시 강서구 곰달래로 136,157908,7781.0,8,1,NaN,126.847975,37.530511
677380,12555061,명랑시대쌀핫도그,NaN,Q,음식,Q07,패스트푸드,Q07A03,핫도그,I56192,...,2623010300103960003051631,NaN,부산광역시 부산진구 새싹로 28,614849,47253.0,NaN,NaN,NaN,129.057382,35.160263
677394,12560297,명랑시대쌀핫도그,둔촌역점,Q,음식,Q07,패스트푸드,Q07A03,핫도그,I56192,...,1174010800104390013003975,NaN,서울특별시 강동구 양재대로 1329,134846,5405.0,NaN,NaN,NaN,127.134816,37.525194
678603,12503900,명랑시대쌀핫도그,NaN,Q,음식,Q07,패스트푸드,Q07A03,핫도그,I56192,...,2626010400100910003017399,NaN,부산광역시 동래구 안남로31번길 6,607801,47893.0,NaN,NaN,NaN,129.095951,35.194506
681176,12606153,명랑시대쌀핫도그,천호점,Q,음식,Q07,패스트푸드,Q07A03,핫도그,I56192,...,1174010900104120003011894,NaN,서울특별시 강동구 천호대로157길 49,134872,5329.0,NaN,NaN,NaN,127.127620,37.539891
681711,12606481,명랑시대쌀핫도그,NaN,Q,음식,Q07,패스트푸드,Q07A03,핫도그,I56192,...,1141011700101330030020862,NaN,서울특별시 서대문구 증가로 13-9,120825,3703.0,NaN,1,NaN,126.931092,37.569118
681960,12592445,명랑시대쌀핫도그,외대점,Q,음식,Q07,패스트푸드,Q07A03,핫도그,I56192,...,1123011000103050132003719,NaN,서울특별시 동대문구 휘경로 22,130831,2441.0,NaN,NaN,NaN,127.062278,37.595346
682651,12609461,명랑시대쌀핫도그,마천점,Q,음식,Q07,패스트푸드,Q07A03,핫도그,I56192,...,1171011400101520003018603,NaN,서울특별시 송파구 마천로45길 41,138819,5752.0,NaN,NaN,NaN,127.151820,37.499241
686083,12585190,명랑시대쌀핫도그,쌍문점,Q,음식,Q07,패스트푸드,Q07A03,핫도그,I56192,...,1132010500107230000007124,신원주상복합2차아파트,서울특별시 도봉구 해등로 190,132897,1394.0,NaN,NaN,NaN,127.035920,37.658161
686391,12492624,명랑시대쌀핫도그,NaN,Q,음식,Q07,패스트푸드,Q07A03,핫도그,I56192,...,2638010400105880006021107,NaN,부산광역시 사하구 하신번영로201번길 1,604838,49431.0,NaN,NaN,NaN,128.958163,35.098891
687664,12611527,명랑시대쌀핫도그,NaN,Q,음식,Q07,패스트푸드,Q07A03,핫도그,I56192,...,1129013400105500002000001,길음뉴타운,서울특별시 성북구 길음로 33,136731,2720.0,NaN,NaN,NaN,127.022076,37.605048
688113,12549547,명랑시대쌀핫도그,NaN,Q,음식,Q07,패스트푸드,Q07A03,핫도그,I56192,...,1111015600101080000014908,NaN,서울특별시 종로구 종로 112,110123,3192.0,NaN,NaN,NaN,126.989966,37.570042
689988,12541244,명랑시대쌀핫도그,NaN,Q,음식,Q07,패스트푸드,Q07A03,핫도그,I56192,...,2626010500102150001016519,NaN,부산광역시 동래구 충렬대로249번길 62,607020,47810.0,NaN,NaN,NaN,129.086987,35.204079
690365,12543208,명랑시대쌀핫도그,NaN,Q,음식,Q07,패스트푸드,Q07A03,핫도그,I56192,...,1135010500104490008019854,한보빌딩,서울특별시 노원구 한글비석로 459,139820,1679.0,NaN,1,NaN,127.066923,37.664077
691056,12542229,명랑시대쌀핫도그,위례신도시점,Q,음식,Q07,패스트푸드,Q07A03,핫도그,I56192,...,1171010900103930003000001,송파와이즈더샵,서울특별시 송파구 위례광장로 270,138926,5852.0,NaN,NaN,NaN,127.143659,37.477061
691488,12492732,명랑시대쌀핫도그,NaN,Q,음식,Q07,패스트푸드,Q07A03,핫도그,I56192,...,1135010500111320102008857,NaN,서울특별시 노원구 동일로 1672,139838,1625.0,NaN,NaN,NaN,127.055542,37.677547
691701,12505035,명랑시대쌀핫도그,안락점,Q,음식,Q07,패스트푸드,Q07A03,핫도그,I56192,...,2626010200101510070018209,NaN,부산광역시 동래구 연안로 51,607825,47898.0,NaN,NaN,NaN,129.107421,35.192554
692141,12507309,명랑시대쌀핫도그,광장점,Q,음식,Q07,패스트푸드,Q07A03,핫도그,I56192,...,1121510300102010008000001,진넥스베르디엠,서울특별시 광진구 광나루로 604,143821,5034.0,NaN,1,102,127.094897,37.541573
692337,12484759,명랑시대쌀핫도그,낙성대역점,Q,음식,Q07,패스트푸드,Q07A03,핫도그,I56192,...,1162010100116320007023988,반석빌딩,서울특별시 관악구 봉천로 602,151832,8793.0,NaN,NaN,NaN,126.963895,37.475981
692381,12492897,명랑시대쌀핫도그,신대방역점,Q,음식,Q07,패스트푸드,Q07A03,핫도그,I56192,...,1162010200105170002014412,소준빌딩,서울특별시 관악구 신사로 102,151873,8702.0,NaN,NaN,NaN,126.913786,37.487038
692726,12505383,명랑시대쌀핫도그,등촌점,Q,음식,Q07,패스트푸드,Q07A03,핫도그,I56192,...,1150010200106960000025433,세신그린코아빌딩,서울특별시 강서구 공항대로41길 51,157930,7586.0,NaN,1,NaN,126.845764,37.560224
694193,12509250,명랑시대쌀핫도그,시흥점,Q,음식,Q07,패스트푸드,Q07A03,핫도그,I56192,...,1154510300108830001006014,NaN,서울특별시 금천구 금하로 630,153858,8628.0,NaN,1,NaN,126.901121,37.454654
694271,12503112,명랑시대쌀핫도그,NaN,Q,음식,Q07,패스트푸드,Q07A03,핫도그,I56192,...,2635010300112910811013636,동민약국,부산광역시 해운대구 재반로 198-1,612814,48030.0,NaN,NaN,NaN,129.130831,35.194907
694369,12522345,명랑시대쌀핫도그,NaN,Q,음식,Q07,패스트푸드,Q07A03,핫도그,I56192,...,2638010600100860006038520,다대롯데캐슬블루,부산광역시 사하구 다송로 23,604052,49515.0,NaN,NaN,NaN,128.982853,35.066090
694712,12511700,명랑시대쌀핫도그,NaN,Q,음식,Q07,패스트푸드,Q07A03,핫도그,I56192,...,1135010300102080018014411,NaN,서울특별시 노원구 공릉로 208,139800,1814.0,NaN,1,NaN,127.077760,37.628265
694723,12520251,명랑시대쌀핫도그,성신여대점,Q,음식,Q07,패스트푸드,Q07A03,핫도그,I56192,...,1129011600100010026044899,NaN,서울특별시 성북구 동소문로22길 6,136051,2845.0,NaN,NaN,NaN,127.017379,37.592701
695610,12520338,명랑시대쌀핫도그,내발산점,Q,음식,Q07,패스트푸드,Q07A03,핫도그,I56192,...,1150010600107500005000001,발산시티타워,서울특별시 강서구 수명로 74,157937,7635.0,NaN,1,NaN,126.826178,37.552579
695701,12510365,명랑시대쌀핫도그,수영점,Q,음식,Q07,패스트푸드,Q07A03,핫도그,I56192,...,2650010500100030058002186,NaN,부산광역시 수영구 남천동로108번길 31,613813,48304.0,NaN,NaN,NaN,129.113055,35.146703
696168,12524042,명랑시대쌀핫도그,목1동점,Q,음식,Q07,패스트푸드,Q07A03,핫도그,I56192,...,1147010200109230015000001,굿모닝탑,서울특별시 양천구 목동서로 221,158051,7995.0,NaN,1,NaN,126.870748,37.527695

In [93]:
df[df.상호명.str.contains("명랑")]

ValueError: cannot index with vector containing NA / NaN values

In [ ]:
df.info()

In [94]:
df[df.시도코드 >10]

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,19911397,커피빈,코리아선릉로93길점,Q,음식,Q12,커피점/카페,Q12A01,커피전문점/카페/다방,I56220,...,1168010100106960042022041,NaN,서울특별시 강남구 선릉로93길 6,135080,6149.0,NaN,NaN,NaN,127.047883,37.505675
1,19911801,프로포즈,NaN,Q,음식,Q09,유흥주점,Q09A01,호프/맥주,I56219,...,1154510200101620001017748,NaN,서울특별시 금천구 가산로 34-6,153010,8545.0,NaN,1,NaN,126.899220,37.471711
2,19912201,싱싱커피&토스트,NaN,Q,음식,Q07,패스트푸드,Q07A10,토스트전문,I56192,...,2653010400105780000002037,산업용품유통상가,부산광역시 사상구 괘감로 37,617726,46977.0,NaN,1,26,128.980455,35.159774
3,19905471,와라와라호프,NaN,Q,음식,Q09,유흥주점,Q09A01,호프/맥주,I56219,...,1168010600106040000014378,대치상가,서울특별시 강남구 남부순환로 2933,135280,6280.0,NaN,1,NaN,127.061026,37.493922
4,19932756,가락사우나내스낵,NaN,F,생활서비스,F09,대중목욕탕/휴게,F09A02,사우나/증기탕/온천,S96121,...,1171010500102560005010490,NaN,서울특별시 송파구 가락로 71,138846,5690.0,NaN,1,NaN,127.104071,37.500249
5,19975850,허술한집,NaN,Q,음식,Q04,분식,Q04A01,라면김밥분식,I56194,...,1150010800100450031005883,NaN,서울특별시 강서구 공항대로3길 9,157812,7619.0,NaN,1,NaN,126.809957,37.562013
6,19976567,씨유씨로지스틱스,NaN,D,소매,D03,종합소매점,D03A01,편의점,G47122,...,1114016800100050002022586,순화빌딩,서울특별시 중구 서소문로 89,100731,4516.0,NaN,NaN,1501,126.970813,37.562587
7,19977290,피자마루,약수점,Q,음식,Q07,패스트푸드,Q07A01,피자전문,I56192,...,1114016200103720095000001,현진빌딩,서울특별시 중구 동호로7길 37,100450,4596.0,NaN,1,NaN,127.010861,37.552153
8,19979419,원일슈퍼,NaN,D,소매,D03,종합소매점,D03A02,수퍼마켓,G47121,...,1174010900103150006009092,원일빌딩,서울특별시 강동구 올림픽로92길 6,134020,5323.0,NaN,1,NaN,127.127190,37.547655
9,19979960,홍능갈비,NaN,Q,음식,Q01,한식,Q01A02,갈비/삼겹살,I56111,...,1150010300110860003013118,NaN,서울특별시 강서구 화곡로18길 31,157010,7718.0,NaN,1,NaN,126.836078,37.538927
10,19980199,프렌즈피씨방,NaN,N,관광/여가/오락,N01,PC/오락/당구/볼링등,N01A01,인터넷PC방,R91222,...,1147010300101460001014147,NaN,서울특별시 양천구 남부순환로 353,158090,7920.0,NaN,1,NaN,126.828910,37.535667
11,19980266,진커피호프,NaN,Q,음식,Q09,유흥주점,Q09A01,호프/맥주,I56219,...,1147010100109470004003423,NaN,서울특별시 양천구 오목로 154,158070,8019.0,NaN,1,NaN,126.854423,37.524654
12,19980870,김명희자연비누,NaN,D,소매,D03,종합소매점,D03B04,시장/종합상가,G47129,...,1147010100102940005005912,NaN,서울특별시 양천구 신목로5길 14,158070,8014.0,NaN,2,NaN,126.872446,37.517863
13,19983964,대성정육점,NaN,D,소매,D01,음/식료품소매,D01A03,정육점,G47212,...,1114016200100430014023177,NaN,서울특별시 중구 다산로36길 93,100815,4584.0,NaN,1,NaN,127.019447,37.560271
14,19969945,에브리돈,NaN,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,1141011900103070003002306,NaN,서울특별시 서대문구 응암로 65,120130,3681.0,NaN,1,NaN,126.910288,37.579029
15,19971229,라이브7080,NaN,Q,음식,Q09,유흥주점,Q09A10,룸살롱/단란주점,I56211,...,1168010800101060018005893,NaN,서울특별시 강남구 언주로136길 7,135010,6058.0,NaN,NaN,NaN,127.036140,37.517348
16,19971398,우리식당,NaN,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,1121510700102070003018172,NaN,서울특별시 광진구 광나루로26길 16,143926,5022.0,NaN,NaN,NaN,127.076812,37.545461
17,19973708,왕실,NaN,Q,음식,Q12,커피점/카페,Q12A01,커피전문점/카페/다방,I56220,...,1114012700101050000019781,NaN,서울특별시 중구 남대문로 52-13,100810,4535.0,NaN,1,NaN,126.982419,37.562274
18,19974666,신호건강원,NaN,D,소매,D10,건강/미용식품,D10A07,건강원,G47216,...,1150010300103690053013643,NaN,서울특별시 강서구 가로공원로82길 42-3,157010,7765.0,NaN,1,NaN,126.840285,37.535419
19,19989422,Mr.피터팬,NaN,Q,음식,Q04,분식,Q04A01,라면김밥분식,I56194,...,1171010300103990017025154,송주빌라,서울특별시 송파구 올림픽로45길 22,138040,5537.0,NaN,1,NaN,127.115873,37.527477
20,19991286,GOVI,NaN,Q,음식,Q09,유흥주점,Q09A01,호프/맥주,I56219,...,1153010200107670148021210,NaN,서울특별시 구로구 도림로 53,152050,8314.0,NaN,1,NaN,126.889734,37.488625
21,19999875,제이씨코퍼레이션,NaN,D,소매,D02,선물/팬시/기념품,D02A05,토산품/기념품점,G47842,...,1156012700100240000037460,삼천리아파트,서울특별시 영등포구 선유서로 115,150103,7269.0,101,NaN,804,126.885320,37.526139
22,20001640,에터미,NaN,D,소매,D16,화장품소매,D16A01,화장품판매점,G47813,...,1162010300110620002023715,NaN,서울특별시 관악구 남현1길 38-9,151800,8806.0,NaN,NaN,NaN,126.979695,37.475560
23,20002036,서울소망흑염소,NaN,D,소매,D10,건강/미용식품,D10A07,건강원,G47216,...,1154510300109010024005627,NaN,서울특별시 금천구 시흥대로50길 30,153030,8630.0,NaN,1,NaN,126.903743,37.451525
24,20004707,커피빈,코리아교대점,Q,음식,Q12,커피점/카페,Q12A01,커피전문점/카페/다방,I56220,...,1165010800116570005024412,카이스시스템빌딩,서울특별시 서초구 서초중앙로 118,137070,6634.0,NaN,1,NaN,127.014217,37.492388
25,20006330,코롱식당,NaN,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,1154510100100600004015530,코오롱테크노밸리,서울특별시 금천구 디지털로9길 56,153770,8512.0,NaN,NaN,102,126.886859,37.480390
26,19993199,고려대학교교육관쎄리오점,NaN,Q,음식,Q12,커피점/카페,Q12A01,커피전문점/카페/다방,I56220,...,1129012500100010002039525,고려대학교안암캠퍼스(인문사회계),서울특별시 성북구 안암로 145,136701,2841.0,NaN,1,32,127.031702,37.588485
27,19996819,전주식당,NaN,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,1153010200104060010000019,구로치안센터,서울특별시 구로구 경인로 577,152887,8212.0,D,NaN,17,126.880898,37.504067
28,19998566,SKY,NaN,Q,음식,Q04,분식,Q04A01,라면김밥분식,I56194,...,1162010100116040034030449,NaN,서울특별시 관악구 관악로12길 23,151050,8788.0,NaN,NaN,NaN,126.953735,37.478135
29,19999456,다락방,NaN,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,1144010200102550023002336,NaN,서울특별시 마포구 마포대로 112-5,121803,4213.0,NaN,1,NaN,126.952127,37.544646
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
696489,12518884,쿱스토어,양천목동점,Q,음식,Q08,제과제빵떡케익,Q08A01,제과점,I56191,...,1147010200107720006000001,선훈아이엔지빌딩,서울특별시 양천구 목동중앙남로 3,158818,7964.0,NaN,NaN,NaN,126.869281,37.534943
696490,12518894,황진이,NaN,Q,음식,Q09,유흥주점,Q09A10,룸살롱/단란주점,I56211,...,1130510100100420212027917,유창빌딩,서울특별시 강북구 월계로 7,142804,1220.0,NaN,NaN,NaN,127.031053,37.609708
696491,12520154,다이다이,NaN,Q,음식,Q09,유흥주점,Q09A01,호프/맥주,I56219,...,1174010500104390000003220,NaN,서울특별시 강동구 양재대로 1448,134814,5356.0,NaN,NaN,NaN,127.139319,37.535066
696492,12520159,마자리스,NaN,Q,음식,Q06,양식,Q06A01,정통양식/경양식,I56114,...,1111016500101910000009707,NaN,서울특별시 종로구 율곡로 215-6,110500,3100.0,NaN,NaN,NaN,127.002863,37.576531
696493,12520532,영철닭발,NaN,Q,음식,Q05,닭/오리요리,Q05A10,닭내장/닭발요리,I56111,...,1138010800100140007018621,NaN,서울특별시 은평구 서오릉로 95,122895,3404.0,NaN,1,113,126.920576,37.608254
696494,12520533,GS25,편의점,D,소매,D03,종합소매점,D03A01,편의점,G47122,...,1150010300100240552016506,NaN,서울특별시 강서구 까치산로 71,157866,7679.0,NaN,1,NaN,126.846801,37.545060
696495,12520534,우리오리,NaN,Q,음식,Q06,양식,Q06A01,정통양식/경양식,I56114,...,2611012200100520007007445,NaN,부산광역시 중구 흑교로45번길 32,600083,48966.0,NaN,NaN,7,129.021707,35.103817
696496,12521663,세븐일레븐,부산온천금강점,D,소매,D03,종합소매점,D03A01,편의점,G47122,...,2626010800100460006014160,성완아이렉스,부산광역시 동래구 금강로 160-1,607831,47708.0,NaN,NaN,NaN,129.081786,35.222631
696497,12521668,home101,NaN,Q,음식,Q04,분식,Q04A01,라면김밥분식,I56194,...,1117012100100320028015280,NaN,서울특별시 용산구 새창로20길 3,140832,4356.0,NaN,NaN,NaN,126.959446,37.538322
696498,12521920,스시훈,NaN,Q,음식,Q03,일식/수산물,Q03A03,음식점-초밥전문,I56113,...,1144010900100950001006362,NaN,서울특별시 마포구 숭문길 34,121872,4138.0,NaN,NaN,NaN,126.945527,37.548029
696499,12521926,온족,NaN,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,2647010200104490027007654,NaN,부산광역시 연제구 과정로287번길 6,611815,47555.0,NaN,NaN,NaN,129.095689,35.188037
696500,12521927,엄지척대게,NaN,Q,음식,Q03,일식/수산물,Q03A10,바닷가재/게요리전문,I56111,...,2623011100105450003004393,NaN,부산광역시 부산진구 가야대로482번길 35,614813,47327.0,NaN,NaN,NaN,129.024815,35.151412
696501,12521928,피러팻,NaN,Q,음식,Q12,커피점/카페,Q12A01,커피전문점/카페/다방,I56220,...,1120011400106850489027875,NaN,서울특별시 성동구 서울숲2길 8,133825,4768.0,NaN,NaN,NaN,127.039520,37.547515
696502,12521929,이미경맛국수,NaN,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,2623010300102590003022691,NaN,부산광역시 부산진구 서면문화로 8-4,614844,47256.0,NaN,NaN,NaN,129.058129,35.158553
696503,12521933,맛의축제,NaN,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,1121510100102330053026447,NaN,서울특별시 광진구 동일로72길 28,143903,4912.0,NaN,1,NaN,127.079030,37.565644
696504,12522174,돈통,NaN,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,1162010100104640041000001,은선파인빌,서울특별시 관악구 중앙길 133,151823,8747.0,1,NaN,NaN,126.947900,37.486301
696505,12522182,백궁양꼬치,NaN,Q,음식,Q09,유흥주점,Q09A03,꼬치구이전문점,I56219,...,1150010300109270006024868,NaN,서울특별시 강서구 강서로5나길 118,157910,7776.0,NaN,NaN,NaN,126.841581,37.528448
696506,12522184,맷돌빈대떡,NaN,Q,음식,Q09,유흥주점,Q09A01,호프/맥주,I56219,...,1126010300102070033031717,NaN,서울특별시 중랑구 중랑역로 6,131878,2117.0,NaN,NaN,NaN,127.077029,37.594786
696507,12522185,구포고깃집,NaN,Q,음식,Q01,한식,Q01A99,기타고기요리,I56111,...,2632010500107000054008328,NaN,부산광역시 북구 시랑로 9-1,616803,46600.0,NaN,NaN,NaN,129.004507,35.204620
696508,12522511,양곱창정말,NaN,Q,음식,Q01,한식,Q01A03,곱창/양구이전문,I56111,...,2623010400108410239031956,NaN,부산광역시 부산진구 범일로154번길 50,614827,47363.0,NaN,NaN,NaN,129.062117,35.143672
696509,12522525,이레찌개마을막국수,NaN,Q,음식,Q04,분식,Q04A02,국수/만두/칼국수,I56194,...,1123010300108920048032069,NaN,서울특별시 동대문구 약령서길 36,130864,2569.0,NaN,NaN,NaN,127.036273,37.579944
696510,12522572,투썸플레이스,아차산역점,Q,음식,Q12,커피점/카페,Q12A01,커피전문점/카페/다방,I56220,...,1121510200102560012006436,NaN,서울특별시 광진구 천호대로 642,143849,4987.0,NaN,2,1,127.088146,37.553307
696511,12522578,에머이,이태원점,Q,음식,Q09,유흥주점,Q09A01,호프/맥주,I56219,...,1117013000101270012009689,스카이하이,서울특별시 용산구 이태원로 180,140858,4406.0,NaN,NaN,NaN,126.994171,37.534217
696512,12522585,Press,NaN,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,1117013000100040006009022,NaN,서울특별시 용산구 회나무로42길 10,140857,4346.0,NaN,NaN,NaN,126.995646,37.540663
696513,12523217,토미야,NaN,Q,음식,Q03,일식/수산물,Q03A02,음식점-일식,I56113,...,1144012500102530006027901,NaN,서울특별시 마포구 월드컵로 120-1,121847,3971.0,NaN,NaN,NaN,126.907658,37.559110
696514,12523676,J&Y헤어,NaN,F,생활서비스,F01,이/미용/건강,F01A01,여성미용실,S96112,...,1153010700100700011010659,NaN,서울특별시 구로구 고척로22길 78,152803,8266.0,NaN,NaN,NaN,126.847160,37.498219
696515,12523677,젠틀맨클럽,NaN,F,생활서비스,F01,이/미용/건강,F01A01,여성미용실,S96112,...,1132010700105450002015870,NaN,서울특별시 도봉구 우이천로4다길 75,132917,1477.0,NaN,1,NaN,127.039197,37.636950
696516,12523515,어니언베이커리,NaN,Q,음식,Q08,제과제빵떡케익,Q08A01,제과점,I56191,...,1168010100107010000022644,공무원연금공단,서울특별시 강남구 언주로 508,135706,6152.0,NaN,NaN,NaN,127.042725,37.503948
696517,12523558,제퍼,NaN,Q,음식,Q12,커피점/카페,Q12A01,커피전문점/카페/다방,I56220,...,2626010900107490005007920,NaN,부산광역시 동래구 사직로 45,607861,47874.0,NaN,NaN,NaN,129.059911,35.194422
696518,12524154,탐앤탐스,더블유디호텔신림점,Q,음식,Q12,커피점/카페,Q12A01,커피전문점/카페/다방,I56220,...,1162010200114320079000001,NaN,서울특별시 관악구 신림로 349,151892,8760.0,NaN,NaN,NaN,126.929310,37.485503

In [95]:
df[["상호명","위도","경도"]]

                 상호명         위도          경도
0                커피빈  37.505675  127.047883
1               프로포즈  37.471711  126.899220
2           싱싱커피&토스트  35.159774  128.980455
3             와라와라호프  37.493922  127.061026
4           가락사우나내스낵  37.500249  127.104071
5               허술한집  37.562013  126.809957
6           씨유씨로지스틱스  37.562587  126.970813
7               피자마루  37.552153  127.010861
8               원일슈퍼  37.547655  127.127190
9               홍능갈비  37.538927  126.836078
10            프렌즈피씨방  37.535667  126.828910
11             진커피호프  37.524654  126.854423
12           김명희자연비누  37.517863  126.872446
13             대성정육점  37.560271  127.019447
14              에브리돈  37.579029  126.910288
15           라이브7080  37.517348  127.036140
16              우리식당  37.545461  127.076812
17                왕실  37.562274  126.982419
18             신호건강원  37.535419  126.840285
19            Mr.피터팬  37.527477  127.115873
20              GOVI  37.488625  126.889734
21          제이씨코퍼레이션  37.526139  126.885320
22               에터미  37.475560  126.979695
23           서울소망흑염소  37.451525  126.903743
24               커피빈  37.492388  127.014217
25              코롱식당  37.480390  126.886859
26      고려대학교교육관쎄리오점  37.588485  127.031702
27              전주식당  37.504067  126.880898
28               SKY  37.478135  126.953735
29               다락방  37.544646  126.952127
...              ...        ...         ...
696489          쿱스토어  37.534943  126.869281
696490           황진이  37.609708  127.031053
696491          다이다이  37.535066  127.139319
696492          마자리스  37.576531  127.002863
696493          영철닭발  37.608254  126.920576
696494          GS25  37.545060  126.846801
696495          우리오리  35.103817  129.021707
696496         세븐일레븐  35.222631  129.081786
696497       home101  37.538322  126.959446
696498           스시훈  37.548029  126.945527
696499            온족  35.188037  129.095689
696500         엄지척대게  35.151412  129.024815
696501           피러팻  37.547515  127.039520
696502        이미경맛국수  35.158553  129.058129
696503          맛의축제  37.565644  127.079030
696504            돈통  37.486301  126.947900
696505         백궁양꼬치  37.528448  126.841581
696506         맷돌빈대떡  37.594786  127.077029
696507         구포고깃집  35.204620  129.004507
696508         양곱창정말  35.143672  129.062117
696509     이레찌개마을막국수  37.579944  127.036273
696510        투썸플레이스  37.553307  127.088146
696511           에머이  37.534217  126.994171
696512         Press  37.540663  126.995646
696513           토미야  37.559110  126.907658
696514         J&Y헤어  37.498219  126.847160
696515         젠틀맨클럽  37.636950  127.039197
696516       어니언베이커리  37.503948  127.042725
696517            제퍼  35.194422  129.059911
696518          탐앤탐스  37.485503  126.929310

[696519 rows x 3 columns]

In [96]:
filename = r"D:\SHN\PythonProject\스타벅스거르기2.xlsx"

In [97]:
df.groupby("시도명")

In [ ]:
groupf = df.groupby("시도명")

In [ ]:
groupf

In [ ]:
groupf.count()

In [98]:
df.groupby(["시도명","시군구명"]).count()

            상가업소번호    상호명   지점명  상권업종대분류코드  상권업종대분류명  상권업종중분류코드  상권업종중분류명  \
시도명   시군구명
부산광역시 강서구     6016   6016   629       6016      6016       6016      6016
      금정구    15124  15124  1464      15124     15124      15124     15124
      기장군     7996   7996   908       7996      7996       7996      7996
      남구     12922  12922  1260      12922     12922      12922     12922
      동구      9270   9270   688       9270      9270       9270      9270
      동래구    16825  16825  1680      16825     16825      16825     16825
      부산진구   29432  29431  2782      29432     29432      29432     29432
      북구     12328  12328  1260      12328     12328      12328     12328
      사상구    16870  16870  1253      16870     16870      16870     16870
      사하구    18126  18126  1664      18126     18126      18126     18126
      서구      6344   6344   454       6344      6344       6344      6344
      수영구    11782  11782   987      11782     11782      11782     11782
      연제구    12681  12681  1172      12681     12681      12681     12681
      영도구     5690   5690   383       5690      5690       5690      5690
      중구     11537  11537  1151      11537     11537      11537     11537
      해운대구   21975  21975  2630      21975     21975      21975     21975
서울특별시 강남구    50940  50940  6445      50940     50940      50940     50940
      강동구    20272  20272  2064      20272     20272      20272     20272
      강북구    10115  10115  1071      10115     10115      10115     10115
      강서구    18262  18262  2256      18262     18262      18262     18262
      관악구    20087  20087  2232      20087     20087      20087     20087
      광진구    20831  20831  2215      20831     20831      20831     20831
      구로구    16220  16220  1713      16220     16220      16220     16220
      금천구    12679  12679  1198      12679     12679      12679     12679
      노원구    15182  15182  2026      15182     15182      15182     15182
      도봉구    10334  10334  1095      10334     10334      10334     10334
      동대문구   19014  19014  1913      19014     19014      19014     19014
      동작구    12658  12658  1623      12658     12658      12658     12658
      마포구    19209  19209  2449      19209     19209      19209     19209
      서대문구   12082  12082  1702      12082     12082      12082     12082
      서초구    29569  29569  3755      29569     29569      29569     29569
      성동구    13575  13575  1409      13575     13575      13575     13575
      성북구    18040  18040  2031      18040     18040      18040     18040
      송파구    23239  23239  3255      23239     23239      23239     23239
      양천구    13877  13877  1779      13877     13877      13877     13877
      영등포구   23624  23624  2695      23624     23624      23624     23624
      용산구    17129  17129  1635      17129     17129      17129     17129
      은평구    14657  14657  1638      14657     14657      14657     14657
      종로구    21942  21942  1904      21942     21942      21942     21942
      중구     32321  32321  2834      32321     32321      32321     32321
      중랑구    15743  15743  1417      15743     15743      15743     15743

            상권업종소분류코드  상권업종소분류명  표준산업분류코드  ...    건물관리번호    건물명  도로명주소  구우편번호  \
시도명   시군구명                                 ...
부산광역시 강서구        6016      6016      5626  ...      6016   1006   6016   6016
      금정구       15124     15124     14271  ...     15124   4835  15124  15124
      기장군        7996      7996      7478  ...      7996   5414   7996   7996
      남구        12922     12922     12137  ...     12922   8152  12922  12922
      동구         9270      9270      8714  ...      9270   3527   9270   9270
      동래구       16825     16825     15707  ...     16825   4491  16825  16825
      부산진구      29432     29432     27695  ...     29432   8105  29432  29432
      북구        12328     12328     11687  ...     12328   5286  12328  12328
      사상구       16870     16870     15750  ...     16870  11956  16870  16870
      사하구       18126     18126     17016  ...     18126   4006  18126  18126
      서구         6344      6344      6094  ...      6344   1074   6344   6344
      수영구       11782     11782     11108  ...     11782   3879  11782  11782
      연제구       12681     12681     11807  ...     12681   3318  12681  12681
      영도구        5690      5690      5435  ...      5690   1363   5690   5690
      중구        11537     11537     10742  ...     11537   2904  11537  11537
      해운대구      21975     21975     20400  ...     21975  14853  21975  21975
서울특별시 강남구       50940     50940     46622  ...     50940  28926  50940  50940
      강동구       20272     20272     18971  ...     20272   7715  20272  20272
      강북구       10115     10115      9611  ...     10115   3627  10115  10115
      강서구       18262     18262     17050  ...     18262  11446  18262  18262
      관악구       20087     20087     18947  ...     20087   7863  20087  20087
      광진구       20831     20831     19506  ...     20831   6885  20831  20831
      구로구       16220     16220     15249  ...     16220   7493  16220  16220
      금천구       12679     12679     11597  ...     12679   6285  12679  12679
      노원구       15182     15182     14366  ...     15182  10912  15182  15182
      도봉구       10334     10334      9757  ...     10334   3418  10334  10334
      동대문구      19014     19014     17779  ...     19014   4190  19014  19014
      동작구       12658     12658     12003  ...     12658   6434  12658  12658
      마포구       19209     19209     18109  ...     19209   6212  19209  19209
      서대문구      12082     12082     11503  ...     12082   4201  12082  12082
      서초구       29569     29569     27319  ...     29569  20378  29569  29569
      성동구       13575     13575     12659  ...     13575   6677  13575  13575
      성북구       18040     18040     17043  ...     18040   7120  18040  18040
      송파구       23239     23239     21738  ...     23239  13983  23239  23239
      양천구       13877     13877     12973  ...     13877   5170  13877  13877
      영등포구      23624     23624     21911  ...     23624  11794  23624  23624
      용산구       17129     17129     16166  ...     17129   6968  17129  17129
      은평구       14657     14657     13928  ...     14657   4603  14657  14657
      종로구       21942     21942     21221  ...     21942   9691  21942  21942
      중구        32321     32321     30743  ...     32321  16148  32321  32321
      중랑구       15743     15743     14867  ...     15743   7662  15743  15743

            신우편번호   동정보    층정보    호정보     경도     위도
시도명   시군구명
부산광역시 강서구    6016   761    784    814   6016   6016
      금정구   15119  1819   3593   1407  15124  15124
      기장군    7995   452   1685   1115   7996   7996
      남구    12920  2015   3684   1814  12922  12922
      동구     9270  1283   2605   1615   9270   9270
      동래구   16825  2206   5286   1948  16825  16825
      부산진구  29432  4346  11089   4847  29432  29432
      북구    12328  2339   2589   2416  12328  12328
      사상구   16869  1658   4724   2604  16870  16870
      사하구   18125  2243   5750   3129  18126  18126
      서구     6344   227   1229   1269   6344   6344
      수영구   11782  1559   3734   1636  11782  11782
      연제구   12681  1785   3952   2002  12681  12681
      영도구    5689   444    819   1206   5690   5690
      중구    11537   880   2772   3932  11537  11537
      해운대구  21975  3112   6574   4744  21975  21975
서울특별시 강남구   50939  3926  31759   8501  50940  50940
      강동구   20272   937  13865   1993  20272  20272
      강북구   10115   826   6060    714  10115  10115
      강서구   18262   935  14538    970  18262  18262
      관악구   20087  1391  11924   2598  20087  20087
      광진구   20831  1922  11989   1824  20831  20831
      구로구   16220  1419   8860   3091  16220  16220
      금천구   12679   970   9090   1510  12679  12679
      노원구   15181  1644   8835   2963  15182  15182
      도봉구   10334  1545   5665   1666  10334  10334
      동대문구  19014  1099  11511   1518  19014  19014
      동작구   12658   872   7193   1560  12658  12658
      마포구   19209   673  13522   1580  19209  19209
      서대문구  12082   758   7396   1273  12082  12082
      서초구   29568  2779  19550   4833  29569  29569
      성동구   13575   618   7824   1938  13575  13575
      성북구   18040  1394   9305   2327  18040  18040
      송파구   23239  1320  17462   2204  23239  23239
      양천구   13877   981  10561    996  13877  13877
      영등포구  23624  1229  15341   3981  23624  23624
      용산구   17128  1068  11232   1908  17129  17129
      은평구   14657  1481   9537   2045  14657  14657
      종로구   21942  2602  11125   4874  21942  21942
      중구    32321  4062  17026  10176  32321  32321
      중랑구   15742  1656   6797   1476  15743  15743

[41 rows x 37 columns]

In [102]:
#!__*__coding:utf-8__*__

import pandas as pd

df_star = pd.read_excel("스타벅스거르기2.xlsx")
df2 = df_star[["상호명", "시도명", "시군구명"]]
gf = df2.groupby(["상호명", "시도명"]).count()
gf = gf.reset_index()
gf.to_excel("스타벅스_상점수.xlsx")

for i in gf.columns:
    print(i)

print(gf.head())

print(gf.info())

상호명
시도명
시군구명
          상호명    시도명  시군구명
0        스타벅스  부산광역시    93
1        스타벅스  서울특별시   271
2   스타벅스IFC몰점  서울특별시     1
3   스타벅스가든파이브  서울특별시     1
4  스타벅스가락시장역점  서울특별시     1
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 158 entries, 0 to 157
Data columns (total 3 columns):
상호명     158 non-null object
시도명     158 non-null object
시군구명    158 non-null int64
dtypes: int64(1), object(2)
memory usage: 3.8+ KB
None

In [110]:
kf = pd.read_csv(r"D:\SHN\PythonProject\data_draw_korea.csv", engine="python",encoding="utf-8")

In [111]:
kf

     Unnamed: 0     인구수 shortName   x   y        면적     광역시도  행정구역
0             0  202520        강릉  11   4  1040.070      강원도   강릉시
1             1   25589    고성(강원)   9   0   664.190      강원도   고성군
2             2   86747        동해  11   5   180.010      강원도   동해시
3             3   63986        삼척  11   8  1185.800      강원도   삼척시
4             4   76733        속초   9   1   105.250      강원도   속초시
5             5   20809        양구   8   0   700.800      강원도   양구군
6             6   24551        양양  10   2   628.680      강원도   양양군
7             7   34966        영월  10   8  1127.360      강원도   영월군
8             8  313851        원주  10   7   867.300      강원도   원주시
9             9   29260        인제   9   2  1646.080      강원도   인제군
10           10   34242        정선  11   6  1220.670      강원도   정선군
11           11   43189        철원   6   0   899.820      강원도   철원군
12           12  264144        춘천  10   3  1116.350      강원도   춘천시
13           13   44175        태백  11   7   303.570      강원도   태백시
14           14   38439        평창  10   6  1463.650      강원도   평창군
15           15   62957        홍천  10   4  1817.940      강원도   홍천군
16           16   23612        화천   7   0   909.450      강원도   화천군
17           17   39668        횡성  10   5   997.820      강원도   횡성군
18           18   53497        가평   9   3   843.040      경기도   가평군
19           19  955384        고양   4   2   267.330      경기도   고양시
20           20   63227        과천   7   7    35.813      경기도   과천시
21           21  327111        광명   3   3    38.500      경기도   광명시
22           22  290210     광주AAA   8   7   431.840      경기도   광주시
23           23  175676        구리   9   4    33.300      경기도   구리시
24           24  273302        군포   5   8    36.350      경기도   군포시
25           25  326523        김포   2   3   276.640      경기도   김포시
26           26  610300       남양주   8   3   458.440      경기도  남양주시
27           27   90398       동두천   7   2    95.680      경기도  동두천시
28           28  805473        부천   2   4    53.440      경기도   부천시
29           29  911628        성남   7   8   141.820      경기도   성남시
..          ...     ...       ...  ..  ..       ...      ...   ...
199         199  104307        정읍   2  16   692.800     전라북도   정읍시
200         200   21917        진안   4  16   788.940     전라북도   진안군
201         201  145369       서귀포   4  25   870.680  제주특별자치도  서귀포시
202         202  430504        제주   4  24   977.800  제주특별자치도   제주시
203         203   37690        계룡   4  12    60.700     충청남도   계룡시
204         204  102371        공주   4  10   940.710     충청남도   공주시
205         205   51134        금산   3  13   576.280     충청남도   금산군
206         206  112516        논산   3  12   554.980     충청남도   논산시
207         207  153415        당진   2   9   694.130     충청남도   당진시
208         208   96133        보령   2  11   568.220     충청남도   보령시
209         209   64652        부여   2  12   624.510     충청남도   부여군
210         210  158771        서산   1  10   739.150     충청남도   서산시
211         211   51776        서천   2  13   363.400     충청남도   서천군
212         212  281938        아산   3   9   542.200     충청남도   아산시
213         213   76757        예산   3  10   543.100     충청남도   예산군
214         214  584912        천안   4   9   636.500     충청남도   천안시
215         215   29671        청양   3  11   479.670     충청남도   청양군
216         216   56489        태안   1   9   504.820     충청남도   태안군
217         217   87904        홍성   2  10   443.900     충청남도   홍성군
218         218   33297        괴산   7  11   842.000     충청북도   괴산군
219         219   27130        단양   7  10   781.070     충청북도   단양군
220         220   30685        보은   7  12   584.450     충청북도   보은군
221         221   46524        영동   6  14   845.010     충청북도   영동군
222         222   47599        옥천   6  13   537.130     충청북도   옥천군
223         223   86441        음성   5  10   521.050     충청북도   음성군
224         224  127462        제천   8  10   882.470     충청북도   제천시
225         225   34480        증평   6  11    81.840     충청북도   증평군
226         226   62809        진천   5  11   406.080     충청북도   진천군
227         227  790216        청주   6  12   932.510     충청북도   청주시
228         228  198077        충주   6  10   983.700     충청북도   충주시

[229 rows x 8 columns]

In [112]:
gf

                  상호명    시도명  시군구명
0                스타벅스  부산광역시    93
1                스타벅스  서울특별시   271
2           스타벅스IFC몰점  서울특별시     1
3           스타벅스가든파이브  서울특별시     1
4          스타벅스가락시장역점  서울특별시     1
5        스타벅스가산디지털단지점  서울특별시     1
6          스타벅스강남에비뉴점  서울특별시     1
7            스타벅스강변역점  서울특별시     1
8        스타벅스강북구청사거리점  서울특별시     1
9          스타벅스건국클래식점  서울특별시     1
10           스타벅스경복궁역  서울특별시     1
11           스타벅스광안비치  부산광역시     1
12           스타벅스광운대점  서울특별시     1
13            스타벅스광장점  서울특별시     1
14          스타벅스광화문역점  서울특별시     1
15           스타벅스광화문점  서울특별시     1
16           스타벅스교대역점  서울특별시     1
17        스타벅스구로디지털로점  서울특별시     1
18    스타벅스구로에이스트윈타워1점  서울특별시     1
19        스타벅스구로하이엔드점  서울특별시     1
20           스타벅스구산역점  서울특별시     1
21         스타벅스금정이마트점  부산광역시     1
22          스타벅스금천독산점  서울특별시     1
23         스타벅스길동사거리점  서울특별시     1
24        스타벅스남부터미널2점  서울특별시     1
25         스타벅스남산스테이트  서울특별시     1
26         스타벅스노원케이티점  서울특별시     1
27           스타벅스논현힐탑  서울특별시     1
28         스타벅스대치사거리점  서울특별시     1
29            스타벅스대치점  서울특별시     1
..                ...    ...   ...
128          스타벅스종로평창  서울특별시     1
129          스타벅스중계역점  서울특별시     1
130         스타벅스중랑구청점  서울특별시     1
131          스타벅스중랑역점  서울특별시     1
132       스타벅스차병원사거리점  서울특별시     1
133        스타벅스천호로데오점  서울특별시     1
134        스타벅스청담사거리점  서울특별시     1
135         스타벅스청량리역점  서울특별시     1
136          스타벅스충정타워  서울특별시     1
137      스타벅스커리학동사거리점  서울특별시     1
138      스타벅스커피가산그레이트  서울특별시     1
139      스타벅스커피가산브이타워  서울특별시     1
140      스타벅스커피강남대로신사  서울특별시     1
141        스타벅스커피마포염리  서울특별시     1
142       스타벅스커피서강대흥역  서울특별시     1
143  스타벅스커피신도림디큐브시티2F  서울특별시     1
144  스타벅스커피신도림디큐브시티B2  서울특별시     1
145    스타벅스커피여의도IFC1F  서울특별시     1
146       스타벅스커피여의도호성  서울특별시     1
147         스타벅스커피홍대역  서울특별시     1
148       스타벅스코엑스사거리점  서울특별시     1
149       스타벅스포스코사거리점  서울특별시     1
150          스타벅스학여울점  서울특별시     1
151       스타벅스한성대입구역점  서울특별시     1
152          스타벅스합정역점  서울특별시     1
153           스타벅스합정점  서울특별시     1
154      스타벅스현대디큐브B2점  서울특별시     1
155        스타벅스홍대삼거리점  서울특별시     1
156          스타벅스화곡동점  서울특별시     1
157         스타벅스황학캐슬점  서울특별시     1

[158 rows x 3 columns]

In [113]:
gf

                  상호명    시도명  시군구명
0                스타벅스  부산광역시    93
1                스타벅스  서울특별시   271
2           스타벅스IFC몰점  서울특별시     1
3           스타벅스가든파이브  서울특별시     1
4          스타벅스가락시장역점  서울특별시     1
5        스타벅스가산디지털단지점  서울특별시     1
6          스타벅스강남에비뉴점  서울특별시     1
7            스타벅스강변역점  서울특별시     1
8        스타벅스강북구청사거리점  서울특별시     1
9          스타벅스건국클래식점  서울특별시     1
10           스타벅스경복궁역  서울특별시     1
11           스타벅스광안비치  부산광역시     1
12           스타벅스광운대점  서울특별시     1
13            스타벅스광장점  서울특별시     1
14          스타벅스광화문역점  서울특별시     1
15           스타벅스광화문점  서울특별시     1
16           스타벅스교대역점  서울특별시     1
17        스타벅스구로디지털로점  서울특별시     1
18    스타벅스구로에이스트윈타워1점  서울특별시     1
19        스타벅스구로하이엔드점  서울특별시     1
20           스타벅스구산역점  서울특별시     1
21         스타벅스금정이마트점  부산광역시     1
22          스타벅스금천독산점  서울특별시     1
23         스타벅스길동사거리점  서울특별시     1
24        스타벅스남부터미널2점  서울특별시     1
25         스타벅스남산스테이트  서울특별시     1
26         스타벅스노원케이티점  서울특별시     1
27           스타벅스논현힐탑  서울특별시     1
28         스타벅스대치사거리점  서울특별시     1
29            스타벅스대치점  서울특별시     1
..                ...    ...   ...
128          스타벅스종로평창  서울특별시     1
129          스타벅스중계역점  서울특별시     1
130         스타벅스중랑구청점  서울특별시     1
131          스타벅스중랑역점  서울특별시     1
132       스타벅스차병원사거리점  서울특별시     1
133        스타벅스천호로데오점  서울특별시     1
134        스타벅스청담사거리점  서울특별시     1
135         스타벅스청량리역점  서울특별시     1
136          스타벅스충정타워  서울특별시     1
137      스타벅스커리학동사거리점  서울특별시     1
138      스타벅스커피가산그레이트  서울특별시     1
139      스타벅스커피가산브이타워  서울특별시     1
140      스타벅스커피강남대로신사  서울특별시     1
141        스타벅스커피마포염리  서울특별시     1
142       스타벅스커피서강대흥역  서울특별시     1
143  스타벅스커피신도림디큐브시티2F  서울특별시     1
144  스타벅스커피신도림디큐브시티B2  서울특별시     1
145    스타벅스커피여의도IFC1F  서울특별시     1
146       스타벅스커피여의도호성  서울특별시     1
147         스타벅스커피홍대역  서울특별시     1
148       스타벅스코엑스사거리점  서울특별시     1
149       스타벅스포스코사거리점  서울특별시     1
150          스타벅스학여울점  서울특별시     1
151       스타벅스한성대입구역점  서울특별시     1
152          스타벅스합정역점  서울특별시     1
153           스타벅스합정점  서울특별시     1
154      스타벅스현대디큐브B2점  서울특별시     1
155        스타벅스홍대삼거리점  서울특별시     1
156          스타벅스화곡동점  서울특별시     1
157         스타벅스황학캐슬점  서울특별시     1

[158 rows x 3 columns]

In [116]:
result = pd.merge(gf, kf, left_on=["시도명", "시군구명"], right_on=["광역시도", "행정구역"])

In [118]:
result

Empty DataFrame
Columns: [상호명, 시도명, 시군구명, Unnamed: 0, 인구수, shortName, x, y, 면적, 광역시도, 행정구역]
Index: []